name = "NLPModelsIpopt"
uuid = "f4238b75-b362-5c4c-b852-0801c9a21d71"
authors = ["Abel Soares Siqueira <abel.s.siqueira@gmail.com>"]
version = "0.1.0"

[deps]
Ipopt = "b6b21f68-93f8-5de0-b562-5493be1d77c9"
NLPModels = "a4795742-8479-5a88-8948-cc11e1c8c1a6"
SolverTools = "b5612192-2639-5dc1-abfe-fbedd65fab29"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
